version: '3'

services: 
  db:
    image: mysql:latest
    restart: always
    container_name: myphpapp-db
    environment: 
      MYSQL_ROOT_PASSWORD: somepass
      MYSQL_DATABASE: somedatabase
    volumes: 
      - ./data:/var/lib/mysql

  # To run db client docker compose run --rm dbclient
  dbclient:
    image: mysql:latest
    depends_on: 
      - db
    command: mysql -uroot -psomepass -hdb
